<header class="page-header">
	<h4>
		<a href="./docs">Documentation</a> /
		<a href="./docs/{{module.path}}">{{module.label}}</a>
	</h4>
	<h1>{{module.page.label || module.label + " Module"}}</h1>
</header>

<div class="row">
	<div class="col-sm-3" ng-if="!module.isEmpty && module.pages.length > 1">
		<ul class="nav nav-pills nav-stacked">
			<li ng-repeat="page in module.pages" ng-class="{active:page.active}">
				<a href="./{{page.path}}">{{page.label}}</a>
			</li>
		</ul>
	</div>
	<div ng-class="{'col-sm-9':!module.isEmpty && module.pages.length > 1, 'col-sm-12':module.isEmpty || module.pages.length < 2}">
		<?=$this->get("contents")?>
	</div>
	
</div>
