<?php
$code = (int) $this->get("code");
$traceString = $this->get("traceString");
$logs = $this->get("logs");
?>

<h1><?=($code === 404) ? "404 Not Found" : "An error has occurred"?></h1>
<h3><?=$this->get("message", "Unknown")?></h3>

<?php if ($traceString): ?>
<pre><?php echo $this->get("traceString"); ?></pre>
<?php endif; ?>

<?php if ($logs && count($logs)): ?>
<pre><?php 
foreach ($logs as $i => $log) { 
	$date = new \DateTime();
	$date->setTimestamp($log["time"]);

	printf("#%d\t%s\t%s\t(%s:%s)\n", 
		$i+1, 
		$date->format("Y-m-d H:i:s") .".". preg_replace("/^[0-9]+\.([0-9]+)$/", "\\1", $log["time"]), 
		$log["message"], 
		$log["file"], 
		$log["line"]
	);
}
?></pre>
<?php endif; ?>