<div class="row">
	<div class="col-sm-6">
		<article class="block shadow">
			<section class="section body">
				<div class="pull-right">
					<paper-icon-button icon="refresh" ng-if="!loading" ng-click="reload()"></paper-icon-button>
					<paper-spinner active ng-if="loading"></paper-spinner>
				</div>
				<h1>Test Results</h1>
				<p class="lead">
					{{result.summary}}
				</p>
				
				<pre ng-bind-html="result.response"></pre>
			</section>
		</article>
	</div>
</div>