<div id="userMenuWidget" ng-controller="user.MenuCtrl">
	<nav ng-if="!user.isActive">
		<a href="./sign-in">Sign In</a> |
		<a href="./sign-up">Sign Up</a>
	</nav>
	
	<nav ng-if="user.isActive">
		<a href="./sign-out">Sign Out</a>
	</nav>
	
	<div class="account">
		<h4 class="display-name" title="{{user.displayName}}" ng-if="user.isActive">
			<a href="./my/account">{{user.displayName}}</a>
		</h4>
		<p class="email">
			{{user.email}}
		</p>
	</div>
	
</div>