<ul class="nav nav-stacked" ng-controller="unifiedUI.NavigationCtrl">
	<li ng-repeat="page in pages | filter:{visible:true}" ng-class="{active:page.active}">
		<a href="./{{page.path}}" target="{{page.target}}" ng-click="intercept($event, page)">{{page.title}}</a>
		<ul ng-if="(page.pages | filter:{visible:true}).length">
			<li ng-repeat="child in page.pages | filter:{visible:true}" ng-class="{active:child.active}">
				<a href="./{{child.path}}" target="{{child.target}}">{{child.title}}</a>
			</li>
		</ul>
	</li>
</ul>