<script data-cfasync="false" src="./polymer/bower_components/webcomponentsjs/webcomponents.min.js"></script>
<link rel="import" href="./polymer/bower_components/polymer/polymer.html">
<link rel="import" href="./polymer/bower_components/core-icons/core-icons.html">
<link rel="import" href="./polymer/bower_components/core-icons/social-icons.html">
<link rel="import" href="./polymer/bower_components/paper-icon-button/paper-icon-button.html">
<link rel="import" href="./polymer/bower_components/paper-spinner/paper-spinner.html">