<article class="block shadow" shrink="!error.open">
	<section class="alert alert-danger">
		<paper-icon-button icon="close" class="pull-right" ng-click="error.open=false;" style="margin-top: -8px; margin-right: -8px;"></paper-icon-button>
		<h3>{{error.message}}</h3>
	</section>
</article>

<form id="signInForm" class="block shadow" method="post" action="./sign-in.json" target="signInFrame">
	<header class="section header">
		<h1>Sign In</h1>
	</header>
	<section class="section body">
		<div class="form-group">
			<label>
				Email Address
			</label>
			<input type="text" class="form-control input-lg" name="email" required>
		</div>
		<div class="form-group">
			<label class="control-label">
				Password
			</label>
			<input type="password" class="form-control input-lg" name="password" required>
		</div>
		<div class="form-group text-right">
			<input type="submit" class="btn btn-lg btn-primary" value="Sign In">
		</div>
	</section>
</form>
<iframe id="signInFrame" name="signInFrame" style="width: 0; height: 0; visibility: hidden;">
